# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('television', 'Television'), ('computer', 'Computer'), ('appliances', 'Appliances')], max_length=32)),
                ('condition', models.CharField(blank=True, choices=[('brand new', 'Brand New'), ('like new', 'Like New'), ('very good', 'Very Good'), ('good', 'Good'), ('acceptable', 'Acceptable')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_street', models.CharField(max_length=255)),
                ('address_number', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_postal_code', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('status', models.CharField(choices=[('new', 'New'), ('middle', 'Middle'), ('old', 'Old'), ('removed', 'Removed')], default='new', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pindrop.Pin'),
        ),
    ]
