# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pindrop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('middle', 'Middle'), ('old', 'Old'), ('removed', 'Removed'), ('picked up', 'Picked Up')], default='new', max_length=32),
        ),
    ]
