# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pindrop', '0002_auto_20170205_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='address_number',
        ),
    ]
