# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pindrop', '0003_remove_pin_address_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pin',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='address_postal_code',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='user',
        ),
        migrations.AddField(
            model_name='pin',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='pindrop.Address'),
        ),
    ]
